version: '2'
services:
  postgres.dev:
    build:
     context: ../../containers/postgres
     args:
      - DDL_URL=${DDL_URL}
    image: yikkai95/postgres:1.0
    networks:
     - dev
    hostname: postgres
    domainname: dev
  ambari-server.dev:
    build:
      context: ../../containers/ambari-server
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
    image: yikkai95/ambari-server:1.0
    networks:
     - dev
    hostname: ambari-server
    domainname: dev
    ports:
     - "8080:8080"
  master0.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: yikkai95/kylin:1.0
    privileged: true
    networks:
     - dev
    hostname: master0
    domainname: dev
    ports:
     # ZooKeeper
     - "2181:2181"
     # HDFS
     - "8020:8020"
     - "9000:9000"
     - "50090:50090"
     # YARN
     - "8088:8088"
     - "8050:8050"
     - "8025:8025"
     - "8030:8030"
     - "8141:8141"
     - "45454:45454"
     - "10200:10200"
     - "8188:8188"
     - "8190:8190"
     - "19888:19888"
     # HiveServer2
     - "10000:10000"
     - "9999:9999"
     - "9933:9933"
     - "10015:10015"
     # HBase
     - "16000:16000"
     - "16010:16010"
     # Storm
     - "8000:8000"
     - "8744:8744"
     # Oozie
     - "11000:11000"
     - "11443:11443"
     # Knox
     - "8443:8443"
     # Ranger
     - "6080:6080"
     - "6182:6182"
     - "6083:6083"
     - "6183:6183"
     # Grafana
     - "3000:3000"
     # Zeppelin
     - "9995:9995"
     # Kerberos
     #- "88:88"
     # Kylin
     - "7070:7070"
  dn0.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: yikkai95/ambari-slave:1.0
    privileged: true
    networks:
     - dev
    hostname: dn0
    domainname: dev

  dn1.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: yikkai95/ambari-slave:1.0
    privileged: true
    networks:
     - dev
    hostname: dn1
    domainname: dev

networks:
  dev:
    driver: bridge
